apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: prove
spec:
  selector:
    app: postgres
  ports:
    - port: 5433        # 충돌 방지용 서비스 포트
      targetPort: 5432  # 컨테이너 내부 PostgreSQL 포트
  type: ClusterIP
